---
# Mount points for the server export and clients.
backup_mountpoint: /system_backups

# Directory pathes for controller.
backup_dirs:
  - /etc
  - /var/lib/nova
  - /var/lib/glance
  - /var/lib/keystone
  - /var/lib/cinder
  - /var/lib/heat
  - /var/lib/heat-config
  - /var/lib/heat-cfntools
  - /var/lib/rabbitmq
  - /var/lib/neutron
  - /var/lib/haproxy
  - /var/lib/openvswitch
  - /var/lib/redis
  - /srv/node
  - /usr/libexec/os-apply-config/
  - /home/heat-admin
  - /root

# Directory pathes to exclude from the system backups.
backup_excludes:
  - /var/lib/nova/instances
  - /proc
  - /sys
  - /dev
  - /run

# Adjust the name here to reflect the name in the inventory / hosts file.
# 
nfs_client:
  - controller_nodes

nfs_server: 192.168.24.1 


# Configure which service type structure is deployed on the overcloud nodes.
# chose are:
# service_type = standard (classic systemd)
# service_type = containerized (container based services)
service_type: containerized
