---  
- name: package install
  become: yes
  yum:
    name: 
      - rear
      - syslinux
      - genisoimage
    state: present
  tags: 
    - install
  
- name: check rear install
  command: rear -V
  register: rear_version
- debug: "ReaR installed"
  when: '"Relax-and-Recover 2.4" in rear_version.stdout_lines'
  tags: 
    - install

- name: copy rear local config
  template: src=local.conf.j2 dest=/etc/rear/local.conf owner=root group=root
  tags:
    - install
