---  
- name: package install
  become: yes
  yum:
    name: 
      - rear
      - syslinux
      - genisoimage
    state: present
  tags: 
    - install
  
- name: check rear install
  command: /usr/sbin/rear -V
  register: rear_version
  tags:
    - install

- debug:
    msg: "Found ReaR..."
  when: rear_version.stdout.find('Relax-and-Recover') == True
  tags:
    - install

- name: copy rear local config
  become: yes
  template: 
    src: local.conf.j2 
    dest: /etc/rear/local.conf 
    owner: root 
    group: root
    mode: '0644'
    backup: yes
  tags:
    - install
