---  
- name: package install
  become: yes
  yum:
    name: 
      - rear
      - syslinux
      - genisoimage
    state: present
  tags: 
    - install
  
- name: check rear install
  command: /usr/sbin/rear -V
  register: rear_version
  when: "rear_version.stat.exists"
  changed_when: False
  tags:
    - install

- name: copy rear local config
  become: yes
  copy: 
    src: local.conf.j2 
    dest: /etc/rear/local.conf 
    owner: root 
    group: root
    mode: '0644'
    backup: yes
  tags:
    - install
