---  
- name: package install
  become: yes
  yum:
    name: 
      - rear
      - syslinux
      - genisoimage
    state: present
  tags: 
    - install
  
- name: check rear install
  command: /usr/sbin/rear -V
  register: rear_version
  tags:
    - install

- name: copy rear local config
  become: yes
  template: src=local.conf.j2 dest=/etc/rear/local.conf owner=root group=root
  tags:
    - install
