---
# tasks file for rear
- name: Backup client data.
  hosts: 
  - controllers
  - undercloud
  remote_user: heat-admin
  sudo: yes
  tasks:
    - name: Backup client data
      shell: rear -v mkbackup
      register: mkbackup
    - debug: msg="{{ mkbackup.stdout }}"
    - debug: msg="{{ mkbackup.stderr }}"

    - name: Verify file presents
      stat:
        path: {{ backup_path }}
      register: mkbackup_status
    - debug: msg="Found backup image."
      when: mkbackup.stat.exists

    - name: Checksum

- name: Install ReaR Packages
  hosts:
  - controllers
  - undercloud
  tasks:
    - name: package install
      yum:
        name: 
          - rear
          - syslinux
          - genisoimage
        state: present
      tags: 
        - client
      
    - name: check rear install
      command: rear -V
      register: rear_version
    - debug: "ReaR installed"
      when: '"Relax-and-Recover 2.4" in rear_version.stdout_lines'
      tags:
       - client

- name: Rescue image creation.
  hosts: nfs_clients
  remote_user: heat-admin
  sudo: yes
  tasks:
    - name: Create rescue image.
      shell: rear -v mkrescue
      register: mkrescue
    - debug: msg="{{ mkrescue.stdout }}"
    - debug: msg="{{ mkrescue.stderr }}"

    - name: Verify file presents
      stat:
        path: {{ backup_path }}
      register: mkrescue_status
    - debug: msg="Rescue image found."
      when: mkrescue.stat.exist