---
- name: Install ReaR Packages
  hosts: vm
  tasks:
    - name: package install
      yum:
        name: 
          - rear
          - syslinux
          - genisoimage
        state: present
      tags: 
        - client
      
    - name: check rear install
      command: rear -V
      register: rear_version
    - debug: "ReaR installed"
      when: '"Relax-and-Recover 2.4" in rear_version.stdout_lines'
      tags:
       - client
