---
- name: Backup client data.
  hosts: 
  - controllers
  - undercloud
  sudo: yes
  tasks:
    - name: Backup client data
      shell: rear -v mkbackup
      register: mkbackup
    - debug: msg="{{ mkbackup.stdout }}"
    - debug: msg="{{ mkbackup.stderr }}"

    - name: Verify file presents
      stat:
        path: {{ backup_path }}
      register: mkbackup_status
    - debug: msg="Found backup image."
      when: mkbackup.stat.exists
