---
# Task responsible for configuring nfs clients.

- name: Packages for RHEL
  set_fact:
     nfs_client_packages:
        - nfs-common
  when: ansible_distribution == 'RedHat'

- name: Packages for CentOS
  set_fact:
     nfs_client_packages:
        - nfs-utils
  when: ansible_distribution == 'CentOS'

- name: Ensure NFS client is installed.
  yum:
    name: "{{ nfs_client_packages }}"
    state: present

- name: Create mountable dir
  file: 
    path: "{{ backup_mountpoint }}"
    state: directory 
    mode: 755 
    owner: root 
    group: root

- name: set mountpoints
  mount: 
    name: "{{ backup_mountpoint }}" 
    src: "{{hostvars[groups['nfs_server'][0]]['ansible_eth0']['ipv4']['address']}}:/backups" 
    fstype: nfs 
    opts: defaults,nobootwait 
    state: mounted

- name: check mount point.
  file:
    path: "{{ backup_mountpoint }}/nfs_test"
    state: touch

- name: check mount point status
  stat:
    path: "{{ backup_mountpoint }}/nfs_test"
  register: file_stat

- debug:
    msg: "NFS mount test passed."
  when: file_stat.stat.exists == true

- debug:
    msg: "NFS mount failed."
  when: file_stat.stat.exists == false

- name: remove test file.
  file:
    path: "{{ backup_mountpoint }}/nfs_test"
    state: absent

- name: check removal state.
  stat:
    path: "{{ backup_mountpoint }}/nfs_test"
  register: file_stat_rm

- debug:
    msg: "NFS test file clean up passed."
  when: file_stat_rm.stat.exists == false

- debug:
    msg: "NFS test file clean up failed."
  when: file_stat_rm.stat.exists == true
