---
# Create a backup for each database into seperate files.
- name: MySQL service database backup.
  vars:
    - exclude_db:
      - "mysql"
  tasks:
    - name: Get database root password
      shell: |
        /bin/hiera -c /etc/puppet/hiera.yaml mysql::server::root_password
      when: mysql_password is undefined
      register: mysql_password
      become: true
      tags:
       - overcloud_nodes
      
    - name: Get all database names.
      shell: 'mysql -u root -p{{ mysql_password }} -e "show databases;" '
      register: dblist
      tags:
        - overcloud_nodes

    - name: Create database backup.
      mysql_db:
        state: dump
        name: "{{ item }}"
        target: "/tmp/{{ item }}.sql.gzip"
        login_user: root
        login_password: "{{ mysql_password }}"
      with_items: "{{ dblist.stdout_lines | difference(exclude_db) }}"
      tags:
        - overcloud_nodes