# Redis database backup task.
---
- name: Get the Redis masterauth password
  shell: |
    /bin/hiera -c /etc/puppet/hiera.yaml redis::masterauth
  when: redis_masterauth_password is undefined
  register: redis_masterauth_password_cmd_output
  become: true
  no_log: true

- name: Get the Redis VIP
  shell: |
    /bin/hiera -c /etc/puppet/hiera.yaml redis_vip
  when: redis_vip is undefined
  register: redis_vip_cmd_output
  become: true

- name: Convert the Redis VIP if unknown
  set_fact:
    redis_vip: "{{ redis_vip_cmd_output.stdout_lines[0] }}"
  when: redis_vip is undefined

- name: Run the redis backup command
  command: /bin/redis-cli -h {{ redis_vip }} -a {{ redis_masterauth_password }} save
  no_log: true

- name: Copy the Redis dump
  copy:
    src: /var/lib/redis/dump.rdb
    dest: "{{ backup_tmp_dir }}/redis/dump.rdb"
    remote_src: yes
  become: true