---
# Create a backup for each database into seperate files.
- name: MySQL service database backup.
  vars:
    - exclude_db:
      - "mysql"
  tasks:
    - name: Get all database names.
      shell: 'mysql -u root -p{{ vault_root_passwd }} -e "show databases;" '
      register: dblist

    - name: Create database backup.
      mysql_db:
        state: dump
        name: "{{ item }}"
        target: "/tmp/{{ item }}.sql.gzip"
        login_user: root
        login_password: "{{ vault_root_passwd }}"
      with_items: "{{ dblist.stdout_lines | difference(exclude_db) }}"