---
# Tasks responsible for configuring the nfs server.
- name: Create mountable dir
  file: 
    path: "{{ backup_mountpoint }}"
    state: directory 
    mode: 755 
    owner: root 
    group: root

- name: Packages for RHEL
  set_fact:
     nfs_server_packages:
        - nfs-common
        - nfs-kernel-server
  when: ansible_distribution == 'RedHat'

- name: Packages for CentOS
  set_fact:
     nfs_server_packages:
        - nfs-utils
  when: ansible_distribution == 'CentOS'

- name: Ensure NFS utilities are installed.
  yum: 
    name: "{{ nfs_server_packages }}"
    state: present

- iptables_raw:
    name: allow_tcp_2049
    rules: '-A INPUT -s {{ overcloud_net }} -m state --state NEW -p tcp --dport 2049 -j ACCEPT'

- iptables_raw:
    name: allow_tcp_111
    rules: '-A INPUT -s {{ overcloud_net }} -m state --state NEW -p tcp --dport 111 -j ACCEPT'

- name: copy /etc/exports
  become: yes
  template: 
    src: exports.j2 
    dest: /etc/exports 
    owner: root 
    group: root

- name: enable nfs server
  service: 
    name: nfs-server 
    enabled: yes

- name: restart nfs server
  service: 
    name: nfs-server 
    state: restarted
