---
# service map for cloudstash to allow for start / stop or restart of openstack services.
service_map:
  aodh:
    systemd_unit:
      - openstack-aodh-evaluator
      - openstack-aodh-listener
      - openstack-aodh-notifier
  barbican:
    systemd_unit:
      - openstack-barbican-api
  ceilometer:
  ceilometer-agent:
    systemd_unit:
      - openstack-ceilometer-central
      - openstack-ceilometer-compute
      - openstack-ceilometer-polling
      - openstack-ceilometer-ipmi
      - openstack-ceilometer-notification
  cinder:
    systemd_unit:
      - openstack-cinder-api
      - openstack-cinder-scheduler
      - openstack-cinder-volume
  congress:
    systemd_unit:
      - openstack-congress-server
  glance:
    systemd_unit:
      - openstack-glance-api
  gnocchi:
    systemd_unit:
      - openstack-gnocchi-api
  haproxy:
    systemd_unit:
      - haproxy
  heat:
    systemd_unit:
      - openstack-heat-api
      - openstack-heat-engine
      - openstack-heat-api-cfn
  horizon:
    systemd_unit: ""
    container_name:
      - horizon
  ironic:
    systemd_unit:
      - openstack-ironic-api
      - openstack-ironic-conductor
  keepalived:
    systemd_unit:
      - keepalived
  keystone:
    systemd_unit: ""
  manila:
    systemd_unit:
      - openstack-manila-scheduler
      - openstack-manila-share
  mistral:
    systemd_unit:
      - openstack-mistral-api
      - openstack-mistral-engine
      - openstack-mistral-event-engine
      - openstack-mistral-executor
  memcached:
    systemd_unit:
      - memcached
  mysql:
    systemd_unit: mariadb
  neutron:
    systemd_unit: ""
  nova-compute:
    systemd_unit:
      - openstack-nova-compute
      - libvirtd
  nova-controller:
    systemd_unit:
      - openstack-nova-api
      - openstack-nova-conductor
      - openstack-nova-consoleauth
      - openstack-nova-scheduler
      - openstack-nova-novncproxy
  octavia:
    systemd_unit: ""
  openvswitch:
    systemd_unit:
      - openvswitch
      - ovs-vswitchd
  rabbitmq:
    systemd_unit:
      - rabbitmq-server
  redis:
    systemd_unit:
      - redis
  swift:
    systemd_unit:
      - ""
  tripleo-ui:
    systemd_unit:
  zaqar:
    systemd_unit: ""