---
# Service Management playbook.
- name: Service Management.
  hosts: controller_nodes
  serial: 1
  tasks:
    - name: Gather service list
      shell: "systemctl list-unit-files --state=enabled --type=service | awk '/^{{ service_name }}.* enabled$/ {print $1}'"
      args:
        executable: "/bin/bash"
      register: _enabled_services
      changed_when: false
      tags:
        - skip_ansible_lint

    - name: Execute service action
      service:
        name: "{{ service_file }}"
        state: "{{ service_action }}"
      with_items: "{{ (_enabled_services.stdout_lines | difference(service_negate | default([]))) | list }}"
      loop_control:
        loop_var: service_file
##
# TODO looking for a openstack heat template option?
