---
# Service Management playbook.
- name: Service Management.
  hosts: controller_nodes
  serial: 1
  tasks:
    - name: Gather service list
      shell: "systemctl list-unit-files --state=enabled --type=service | awk '/^{{ service_name }}.* enabled$/ {print $1}'"
      args:
        executable: "/bin/bash"
      register: _enabled_services
      changed_when: false

    - name: Execute service action
      service:
        name: "{{ service_name }}"
        state: stopped
      with_items: "{{ (_enabled_services.stdout_lines | difference(service_negate | default([]))) | list }}"
      loop_control:
        loop_var: service_name
      tags:
        - stop_systemctl_services

    - name: Start Service
      service:
        name: "{{ service_name }} "
        state: started
      with_items: "{{ (_enabled_services.stdout_lines | difference(service_negate | default([]))) | list }}"
      loop_control:
        loop_var: service_name
      tags:
        - start_systemctl_services
    
    - name: Gather Container Service Name
      shell: "docker ps -a --format '{{.Names}}'"
      args:
        excutable: "/bin/bash"
      register: container_services
      changed_when: false

    - name: Stop Service Container
      docker_container: 
        name: "{{ items }}"
        state: stopped
      with_items: "{{ container_services.stdout_lines }} "
      tags:
        - stop_container_services
      
    - name: Start Service Container
      docker_container: 
        name: "{{ items }}"
        state: started
        with_items: " {{ container_services.stdout_lines }} "
      tags:
        - start_container_services

    

