# Creates a snapshot on volume 'test_volume'
- name: create and delete snapshot
  hosts: control_plane
  tasks:
  - name: create snapshot
    os_volume_snapshot:
      state: present
      cloud: mordred
      availability_zone: storage_zone
      display_name: snapshot_name
      volume: test_volume
    tags: volume_backup
  - name: delete snapshot
    os_volume_snapshot:
      state: absent
      cloud: mordred
      availability_zone: storage_zone
      display_name: snapshot_name
      volume: test_volume
    tags: volume_delete