---
# tasks file for storage
- hosts: nfs_clients
  remote_user: stack
  sudo: yes

  tasks:
    - name: Ensure NFS client is installed.
      yum: 
        name: 
          - nfs-common
          - firewalld 
        state: present
      tags: clients

    - name: Configure nfs client firewall port.
      firewalld:
       service: nfs
       permanent: true
       state: enabled

    - name: Create mountable dir
      file: path=/system_backup state=directory mode=777 owner=root group=root
      tags: clients

    - name: set mountpoints
      mount: name=/system_backup src={{hostvars[groups['nfs_server'][0]]['ansible_eth0']['ipv4']['address']}}:/backups fstype=nfs opts=defaults,nobootwait dump=0 passno=2 state=mounted
      tags: clients

- hosts: nfs_server
  remote_user: stack
  sudo: yes

  tasks:
    - name: Create mountable dir
      file: path=/backups state=directory mode=777 owner=root group=root
      tags: server

    - name: make sure the mount drive has a filesystem
      filesystem: fstype=ext4 dev={{ mountable_share_drive | default('/dev/xvdb') }}
      tags: server

    - name: set mountpoints
      mount: name=/backups src={{ mountable_share_drive | default('/dev/xvdb') }} fstype=auto opts=defaults,nobootwait dump=0 passno=2 state=mounted
      tags: server

    - name: Ensure NFS utilities are installed.
      yum: 
        name:
        - nfs-common
        - nfs-kernel-server
        state: present
      tags: server

    - name: copy /etc/exports
      template: src=exports.j2 dest=/etc/exports owner=root group=root
      tags: server

    - name: restart nfs server
      service: name=nfs-kernel-server state=restarted
      tags: server