---
# Tasks responsible for configuring the nfs server.
- name: Create mountable dir
  file: 
    path: "{{ backup_mountpoint }}"
    state: directory 
    mode: 777 
    owner: root 
    group: root
  tags: server

- name: make sure the mount drive has a filesystem
  filesystem: 
    fstype: ext4 
    dev: "{{ mountable_share_drive | default('/dev/vdb') }}"
  tags: server

- name: set mountpoints
  mount: 
    name: "{{ backup_mountpoint }}" 
    src: "{{ mountable_share_drive | default('/dev/vdb') }}"
    fstype: auto 
    opts: defaults,nobootwait 
    state: mounted
  tags: server

- name: Packages for RHEL
  set_fact:
     nfs_server_packages:
        - nfs-common
        - nfs-kernel-server
  when: ansible_distribution == 'RedHat'

- name: Packages for CentOS
  set_fact:
     nfs_server_packages:
        - nfs-utils
  when: ansible_distribution == 'CentOS'

- name: Ensure NFS utilities are installed.
  yum: 
    name: "{{ nfs_server_packages }}"

    state: present
  tags: server

- name: copy /etc/exports
  become: yes
  copy: 
    src: exports.j2 
    dest: /etc/exports 
    owner: root 
    group: root
  tags: server

- name: enable nfs server
  service: 
    name: nfs-server 
    enabled: yes
  tags: server

- name: restart nfs server
  service: 
    name: nfs-server 
    state: restarted
  tags: server
