---
# Task responsible for configuring nfs clients.

- name: Packages for RHEL
  set_fact:
     nfs_client_packages:
        - nfs-common
        - firewalld
  when: ansible_distribution == 'RedHat'

- name: Packages for CentOS
  set_fact:
     nfs_client_packages:
        - nfs-utils
        - firewalld
  when: ansible_distribution == 'CentOS'

- name: Ensure NFS client is installed.
  yum:
    name: "{{ nfs_client_packages }}"
    state: present
  tags: 
    - clients

- name: Configure nfs client firewall port.
  firewalld:
    service: nfs
    permanent: true
    state: enabled

- name: Create mountable dir
  file: 
    path: "{{ backup_mountpoint }}"
    state: directory 
    mode: 755 
    owner: root 
    group: root
  tags: 
    - clients

- name: set mountpoints
  mount: 
    name: "{{ backup_mountpoint }}" 
    src: "{{hostvars[groups['nfs_server'][0]]['ansible_eth0']['ipv4']['address']}}:/backups" 
    fstype: nfs 
    opts: defaults,nobootwait 
    state: mounted
  tags: 
    - clients

- name: check mount point.
  file:
    path: "{{ backup_mountpoint }}/nfs_test"
    state: touch
  tags:
    - clients

- name: check mount point status
  stat:
    path: "{{ backup_mountpoint }}/nfs_test"
  register: file_stat
  tags:
    - clients

- debug:
    msg: "NFS mount test passed."
  when: file_stat.stat.exists == true
  tags:
    - clients

- debug:
    msg: "NFS mount failed."
  when: file_stat.stat.exists == false
  tags:
    - clients

- name: remove test file.
  file:
    path: "{{ backup_mountpoint }}/nfs_test"
    state: absent
  tags:
    - clients

- name: check removal state.
  stat:
    path: "{{ backup_mountpoint }}/nfs_test"
  register: file_stat_rm
  tags:
    - clients

- debug:
    msg: "NFS test file clean up passed."
  when: file_stat_rm.stat.exists == false
  tags:
    - clients

- debug:
    msg: "NFS test file clean up failed."
  when: file_stat_rm.stat.exists == true
  tags:
    - clients

