---
- name: Install ReaR packages
  hosts:
    - controller_nodes
    - undercloud
  gather_facts: true
  tags:
    - install
  roles:
    - rear/setup

- name: NFS Server setup.
  hosts: nfs_server
  gather_facts: true
  tags:
    - server
  roles:
    - storage

- name: NFS Client setup.
  hosts: nfs_client
  gather_facts: true
  tags:
    - client
  roles:
    - storage
