---
- name: Install ReaR packages
  hosts:
    - controller_nodes
    - undercloud
  become: yes
  tags:
    - install
  roles:
    - rear/setup

# TODO: change the two plays to become a more generic interface.
#
- name: NFS Server setup.
  hosts: 
    - nfs_server
  become: yes
  roles:
    - storage/nfs_server
  tags: server

- name: NFS Client setup.
  hosts: 
    - nfs_client
  become: yes
  roles:
    - storage/nfs_client
  tags:
    - client
