---
- name: Install ReaR packages
  hosts:
    - controller_nodes
    - undercloud
  gather_facts: false
  become: yes
  tags:
    - install
  roles:
    - rear/setup

# TODO: change the two plays to become a more generic interface.
#
- name: Get NFS Server IP
  hosts: undercloud
  gather_facts: true
  tasks:
    - set_fact:
        nfs_server_ip: "{{ item }}"
      when: "item.startswith('192.168.24')"
      with_items: "{{ ansible_all_ipv4_addresses }}"
    - debug: msg= "{{ nfs_server_ip }}"

- name: NFS Server setup.
  hosts: 
    - nfs_server_ip
  gather_facts: false
  become: yes
  roles:
    - storage/nfs_server
  tags: server

- name: NFS Client setup.
  gather_facts: false
  hosts: 
    - nfs_client
  become: yes
  roles:
    - storage/nfs_client
  tags:
    - client
