---
# Cloudstash Backup Playbook.
- name: Stop all running services
  hosts:
    - controllers
  roles:
    - role: service_manager
  tags: stop_services

- name: Backup databases on controller nodes.
  hosts: controller_nodes
  gather_facts: true
  roles:
    - database
  tags:
    - db_backup

- name: Start System Backup
  hosts:
    - controllers
    # - undercloud
  roles:
  - rear/backup
  tags:
    - backup

- name: Start System Rescue
  hosts:
    - controllers
    # - undercloud
  roles:
  - rear/backup
  tags:
    - rescue

- name: Start all services.
  hosts:
    - controllers
  roles:
    - role: service_manager
  tags: start_services
